DATA ip;
	INFILE 'C:\data\ip.prn';
	INPUT date ip;
	logip = LOG(ip);
	ipg = DIF(logip)*100;
	IF date < 19921231 THEN DELETE;
RUN;
DATA wti;
	INFILE 'C:\data\wti.prn';
	INPUT date wti;
	IF date < 19921231 THEN DELETE;
RUN;
DATA all;
	MERGE wti ip; 
	*wti ip면 월초, ip wti는 월말;
	*By date로 하념 바둑판식으로 결측치가 나옴;
	IF date> 20120629 THEN DELETE;
RUN;
DATA ex01;
	SET all;
		IF date < 20080101 THEN DO;
			int1 = 1;
			int2 = 0;
			wti1 = wti;
			wti2 = 0;
		END;
		ELSE DO;
			int1 = 0;
			int2 = 1;
			wti1 = 0;
			wti2 = wti;
		END;
	RUN;
	PROC REG DATA = ex01;
		MODEL ipg = int1 int2 wti1 wti2/NOINT;
		TEST int1 = int2, wti1 = wti2;
	RUN;
