DATA ip;
		INFILE 'c:\data\ip.prn';
		INPUT date  ip;
		ipg = DIF(LOG(ip))*1200;
RUN;
DATA sp500;
	INFILE 'c:\data\sp500.prn';
	INPUT date sp;
	spg = DIF(LOG(sp))*1200;
RUN;
DATA ex02;
	MERGE ip sp500;
	BY date;
	IF date < 19570101 THEN DELETE;
RUN;
DATA ex02;
	SET ex02;
	spg1 = LAG(spg);
	spg2 = LAG2(spg);
	spg3 = LAG3(spg);
	spg4 = LAG4(spg);
	spg5 = LAG5(spg);
	spg6 = LAG6(spg);
RUN;
PROC REG DATA = ex02;
	MODEL ipg = spg;
	MODEL ipg = spg1;
	MODEL ipg = spg2;
	MODEL ipg = spg3;
	MODEL ipg = spg4;
	MODEL ipg = spg5;
	MODEL ipg = spg6;
RUN;
