DATA sp;
		INFILE 'C:\data\sp500.prn';
		INPUT mon sp; 
		logsp = LOG(sp);
		spg = DIF(logsp)*1200;
RUN;
DATA fyff;
		INFILE 'C:\data\fyff.prn';
		INPUT mon fyff;
		fyff4 = LAG4(fyff);
RUN;
DATA all;
		MERGE sp fyff;
		By mon;
		WHERE 19590101 <= mon < 20120801;
		num = _N_;
RUN;
PROC AUTOREG DATA = all;
	MODEL spg = fyff/NLAG = 1 ARCHTEST DWPROB METHOD = ml MAXIT = 200;
RUN;
