DATA ip;
			INFILE 'c:\data\ip.prn';
			INPUT mon ip;
			ipg = DIF(LOG(ip))*100;
RUN;
DATA sp;
			INFILE 'c:\data\sp500.prn';
			INPUT mon sp;
			spg = DIF(LOG(sp))*100;
RUN;
DATA ex03;
	MERGE ip sp;
	BY mon;
	int = 1;
	WHERE 19570101 < mon < 20120801;
RUN;
PROC REG DATA=ex03;
	MODEL ipg = spg/DW DWPROB;
	OUTPUT OUT = out02 R = resid;
RUN;
PROC IML;
	START reg;
				n = NROW(x);
				k = NCOL(x);
				df = n-k;
				xpx = x`*x;
				xpy = x`*y;
				xpxi = INV(xpx);
				b = xpxi*xpy;
				yhat = x*b;
				e = y-yhat;
				sse = e`*e;
				mse = sse/df;
				covb = mse#xpxi;
				stdb = SQRT(VECDIAG(covb));
				t = b/stdb;
				probt = 1- PROBF(t#t,1,df);
				PRINT "result of regression are" b stdb t probt;
				e1 = LAG(e,1);
				em = e-e1;
				em[1,1] = 0;
				emsq = em`*em;
				dw=emsq/sse;
				PRINT "durbin watson-d is" dw;
	FINISH reg;
	USE ex03;
		READ all VAR{ipg} into y;
		READ all VAR{int spg} into x;
	RUN reg;
QUIT;
DATA ex04;
		SET out02;
		resid1=LAG(resid);
RUN;
PROC REG DATA=ex04;
		MODEL resid = resid1;
RUN;
