DATA ip;
	INFILE 'c:/data/ip.prn';
	INPUT date ip;
	ipg=DIF(LOG(ip))*100;
	IF date<19960231 THEN DELETE;
RUN;
DATA bal;
	INFILE 'c:/data/Monthly_CurrentBalance.prn';
	INPUT date bal;
	IF date<19960231 THEN DELETE;
RUN;
DATA m1;
	INFILE 'c:/data/m1_usa.prn';
	INPUT date m1;
	IF date<19960231 THEN DELETE;
RUN;
DATA wti;
	INFILE 'c:/data/wti.prn';
	INPUT date wti;
	IF date<19960231 THEN DELETE;
RUN;
DATA sp;
	INFILE 'c:/data/sp500.prn';
	INPUT date sp500;
	IF date<19960231 THEN DELETE;
RUN;
DATA ex01;
	MERGE ip bal m1 wti sp;
	IF date>20120701 THEN DELETE;
	int=1;
RUN;
/* (2) structural change를 위한 데이터 생성 */
DATA ex01;
	SET ex01;
	IF date>20070101 THEN DO;
		int1=int;
		int2=0;
		b1=bal;
		b2=0;
		m11=m1;
		m12=0;
		w1=wti;
		w2=0;
		sp1=sp500;
		sp2=0;
		ip1=ip;
		ip2=0;
	END;
	ELSE DO;
		int1=0;
		int2=int;
		b1=0;
		b2=bal;
		m11=0;
		m12=m1;
		w1=0;
		w2=wti;
		sp1=0;
		sp2=sp500;
		ip1=0;
		ip2=ip;
	END;
RUN;
PROC AUTOREG DATA = ex01;
	MODEL ip = bal m1 wti sp500/chow = 132 pchow= 132;
RUN; 

PROC IML;
	USE ex01;
		READ all VAR {ip} INTO y;
		READ all VAR {int bal m1 wti sp} INTO x;
	START reg;
			n=NROW(x);
			k=NCOL(x);
			df=n-k;
			b=(inv(x`*x))*(x`*y);
			yhat=x*b;
			e=y-yhat;
			sse=e`*e;
			mse=sse/df;
			covb=mse*(inv(x`*x));
			stdb=SQRT(VECDIAG(covb));
			t=b/stdb;
			probt=1-PROBF(t#t, 1, df);
			PRINT b stdb t probt;
	FINISH reg;
	RUN reg;
START chow;
	READ all VAR {ip1} INTO y;
	READ all VAR {int1 b1 m11 w1 sp1} INTO x;
RUN reg;
		sse1=sse;
		n1=(x`*x)[1,1];
		df1=n1-k;
READ all VAR {ip2} INTO y;
READ all VAR {int2 b2 m12 w2 sp2} INTO x;
RUN reg;
		sse2=sse;
		n2=n-n1;
		df2=n2-k;
READ all VAR {ip} INTO y;
READ all VAR {int bal m1 wti sp} INTO x;
RUN reg;
		PRINT "Chow test";
		sser=sse1+sse2;
		mse1=sse1/df1;
		mse2=sse2/df2;
		vf=mse1/mse2;
		numer=(sse-sser)/k;
		denom=sser/(n-2*k);
		chow=numer/denom;
		probvf=1-PROBF(vf, df1, df2);
		probvfinv=1-probvf;
		probchow=1-PROBF(chow, k, n-2*k);
		PRINT "Chow test" chow probchow;
		PRINT "compare MSE" mse1 mse2, "F-value" vf, "Probability" probvf probvfinv;
FINISH chow;
RUN chow;
Quit;
PROC IML;
	READ all VAR {ip1} INTO y;
	READ all VAR {int1 b1 m11 w1 sp1} INTO x;
RUN reg;
		sse1=sse;
		n1=(x`*x)[1,1];
		df1=n1-k;
READ all VAR {ip2} INTO y;
READ all VAR {int2 b2 m12 w2 sp2} INTO x;
		RUN reg;
		sse2=sse;
		n2=n-n1;
		df2=n2-k;
READ all VAR {ip} INTO y;
READ all VAR {int bal m1 wti sp} INTO x;
RUN reg;
		PRINT "Chow test";
		sser=sse1+sse2;
		mse1=sse1/df1;
		mse2=sse2/df2;
		vf=mse1/mse2;
		numer=(sse-sser)/k;
		denom=sser/(n-2*k);
		chow=numer/denom;
		probvf=1-PROBF(vf, df1, df2);
		probvfinv=1-probvf;
		probchow=1-PROBF(chow, k, n-2*k);
PRINT "Chow test" chow probchow;
PRINT "compare MSE" mse1 mse2, "F-value" vf, "Probability" probvf probvfinv;
FINISH chow;
RUN chow;
Quit;
Data ip; 
	Infile "C:/data/ip.prn"; 
	Input date ip;
	ipg = DIF(log(ip))*100; IF 19960231<date<20130201 then date = date; ELSE delete;
Run;
Data m1;
	Infile "C:/data/m1_usa.prn"; 
	Input date m1; 
	IF 19960231<date<20130201 then date = date; 
	ELSE delete; 
Run;
Data wti;
	Infile "C:/data/wti.prn";
	Input date wti; 
	IF 19960231<date<20130201 then date = date; 
	ELSE delete; 
Run;
Data ex02; 
	Merge m1 wti ip; 
	IF date>20120701 then delete;
	int = 1; 
Run;
PROC IML; 
	Use ex02; 
	Read all Var {ipg} into y; 
	Read all Var {int m1 wti} into x; name = {"Intercept", "M1", "WTI"};
Start reg; 
		n = nrow(x);
		k = ncol(x);
		df = n-k; 
		xpx = x`*x; 
		xpy = x`*y; 
		xpxi = inv(xpx); 
		b = xpxi*xpy; 
		yhat = x*b; 
		e = y-yhat; 
		sse = e`*e; 
		mse = sse/df;
		covb = mse*xpxi;
		stdb = sqrt(vecdiag(covb));
		t = b/stdb;
		probt = 1-probf(t#t, 1, df);
	Print "regression" name b stdb t probt;
		e1 = lag(e, 1);
		em = e-e1;
		em[1,1] = 0;
		emsq = em`*em;
		dw = emsq/sse;
	Print "Durbin-Watson statistic d" dw;
	Finish reg;
	Print "/*** Original regression ***/";
Run reg;
	Start coe;
		rho = 1-(dw/2);
		x = x[2:n,] - rho*x[1:n-1,];
		y = y[2:n,] - rho*y[1:n-1,];
	Print rho;
	Finish coe;
	Print "/*** Cochrane-Orcutt estimation 1st ***/";
Run coe;
Run reg;
	Print "/*** Cochrane-Orcutt estimation 2nd ***/";
Run coe;
Run reg;
	Print "/*** Cochrane-Orcutt estimation 3rd ***/";
Run coe;
Run reg;
Quit;
PROC AUTOREG Data = ex02;
		Model ipg = m1 wti/nlag = 1 method = ml;
		Model ipg = m1 wti/nlag = 2 method = ml;
		Model ipg = m1 wti/nlag = 3 method = ml;
Run;
