DATA sp;
		INFILE 'C:\data\sp500.prn';
		INPUT mon sp; 
		logsp = LOG(sp);
		spg = DIF(logsp)*1200;
RUN;
DATA ip;
		INFILE 'C:\data\ip.prn';
		INPUT mon ip; 
		logip = LOG(ip);
		ipg = DIF(logip)*1200;
RUN;
DATA fyff;
		INFILE 'C:\data\fyff.prn';
		INPUT mon fyff;
		fyff4 = LAG4(fyff);
RUN;
DATA all;
		MERGE sp fyff ip;
		By mon;
		WHERE 19590101 <= mon < 20120801;
		num = _N_;
RUN;
PROC AUTOREG DATA = all;
	MODEL spg = fyff/NLAG = 1 ARCHTEST DWPROB METHOD = ml MAXIT = 200;
RUN;
PROC GPLOT DATA = all;
	PLOT spg*num;
	SYMBOL v = none c= blue i = join;
RUN;
PROC AUTOREG DATA = all;
	MODEL spg = fyff/NLAG = 1 GARCH = (q=1, p=1)  METHOD = ml MAXIT = 200;
	OUTPUT OUT = out1 CEV = ht;
RUN;
DATA all;
	SET out1;
	st = SQRT(ht);
RUN;
PROC AUTOREG DATA = all;
	MODEL ipg = fyff4 st/NLAG =1 METHOD = ml MAXIT = 200;
	MODEL ipg = fyff4 st/NLAG =2 METHOD = ml MAXIT = 200;
	MODEL ipg = fyff4 st/NLAG =3 METHOD = ml MAXIT = 200;
	MODEL ipg = fyff4 st/NLAG =4 METHOD = ml MAXIT = 200;
	MODEL ipg = fyff4 st/NLAG =5 METHOD = ml MAXIT = 200;
RUN;	
PROC AUTOREG DATA = all;
	MODEL spg = fyff/NLAG = 1  METHOD = ml MAXIT = 200;
RUN;
PROC GPLOT DATA = all;
	PLOT spg*num=1 st*num=2/overlay;
	SYMBOL1 v = none c= black i = join;
	SYMBOL2 v = none c= red i = join;
RUN;
