DATA koex;
			INFILE 'c:\data\koex3.prn';
			INPUT mon koex;
			koexg = DIF(LOG(koex));
RUN;
DATA cli;
			INFILE 'c:\data\cli.prn';
			INPUT mon clik cliu;
RUN;
DATA ex03;
	MERGE koex cli;
	BY mon;
	int =1;
	WHERE 19900101 <= mon <= 20170301;
RUN;
DATA ex03;
	SET ex03;
		clikg = DIF(LOG(clik));
		cliug = DIF(LOG(cliu));
RUN;
PROC ARIMA DATA = ex03;
	IDENTIFY VAR = koexg STATIONARITY = (ADF = 5);
RUN;
PROC ARIMA DATA = ex03;
	IDENTIFY VAR = koex STATIONARITY = (ADF = 5);
RUN;
PROC REG DATA = ex03;
	MODEL koexg = clikg cliug/DW DWPROB;
RUN;
PROC REG DATA = ex03;
	MODEL koex = clik cliu/DW DWPROB;
RUN;
PROC REG DATA = ex03;
	MODEL koexg = clik cliu/DW DWPROB;
RUN;
