DATA kospi;
	INFILE "C:\data\kp200d.prn";
	INPUT date kospi;
	kospig=DIF(LOG(kospi));
RUN;
DATA snp;
	INFILE "C:\data\sp500d.prn";
	INPUT date sp;
	spg=DIF(LOG(sp));
		IF spg>=0 THEN DO;
			IP=1;
			IN=0;
			spgp=spg;
			spgn=0;
		END;
			ELSE DO;
			IP=0;
			IN=1;
			spgp = 0;
			spgn = spg;
		END;
		IP1 = LAG(IP);
		IN1= LAG(IN);
		spgp1 = LAG(spgp);
		spgn1 = LAG(spgn); 
RUN;
DATA all;
	MERGE kospi snp;
	BY date;
	WHERE 20050103 <= date <= 20120831;
RUN;
PROC REG DATA = all;
		MODEL kospig=IP1 IN1 spgp1 spgn1/NOINT;
		TEST IP1 = IN1, spgp1=spgn1;
		MODEL kospig = spgp1;
RUN;
DATA ip;
	INFILE "C:\data\ip.prn";
	INPUT mon ip;
	ipg=DIF(LOG(ip));
	ipg1 = LAG(ipg);
RUN;
DATA fyff;
	INFILE "C:\data\fyff.prn";
	INPUT mon fyff;
	fyff4=LAG4(fyff);
RUN;
DATA all2;
	MERGE ip fyff;
	BY mon;
	WHERE 19590101 <= mon <= 20120701;
RUN;
PROC AUTOREG DATA =all2;
		MODEL ipg = fyff ipg1/NLAG=1 METHOD=ML MAXIT = 200;
		TEST fyff = ipg1/TYPE = wald;
RUN;
